name: ItemProvider
version: '${project.version}'
main: io.github.reconsolidated.itemprovider.ItemProvider
api-version: 1.18
commands:
  itemprovider:
    description: ItemProviderCommand
    permission: itemprovider.admin
    aliases: [itp]